html:
	ipython nbconvert "Certik Keynote.ipynb" --to slides

serve:
	@echo "Open:"
	@echo "http://localhost:8000/Certik%20Keynote.slides.html"
	python -m SimpleHTTPServer

pdf:
	@echo "Open:"
	@echo "http://localhost:8000/Certik%20Keynote.slides.html?print-pdf"
	python -m SimpleHTTPServer
